services:
  api:
    command: uvicorn src.main:main_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"

  postgres:
    ports:
      - "5432:5432"